### ISSUE TITLE
date format should use board default or be configurable

### ISSUE THREAD

**Issue by runewolf** [gn36/phpbb-ext-hookup#38]
Date format should use board default or be configurable.  I.e. December 4, 2015 should look like 12.04.2015 for us Yanks instead of 04.12.2015 .

**Comment by gn36** [comment]
Hi @runewolf, I have now looked into this issue. The date format is actually configurable. There is a language variable that defines this for several occasions. For example, column headings are configurable in the language file. So every user should see the dates according to his language. 

Since there actually is an american english translation of phpBB, I would suggest to simply create an american english translation of the hookup extension as well. You will however need to use the american english translation to actually benefit from that change. Since this is going to be just copy & paste except for the date format, I can create that myself, but I would need you to make me aware of any other en_US specific changes that need to be made.

I don't think putting default board dates or user defined dates into the extension would be useful, though, except for the locations it is already used (in hovers). In most locations, the dates that are put in need to be really short. So a date like "December 4, 2015" as a prefix to the topic would be way too long, the same goes for column headings. I can surely change the date format to "04/23/15 10:55" instead of "23.04.15 10:55" in titles for the "en_us" version, do I need to change anything else?

**Comment by runewolf** [comment]
That would be the only change in can forsee. Everything else looks good.

Thanks,
Allen

**Comment by gn36** [comment]
Alright, I have added en_us as a language. You will only benefit if you actually use that language, obviously.
