### ISSUE TITLE
Fatal error, if User has a language selected, that is not supported by the hookup extension

### ISSUE THREAD

**Issue by BenniGotchi** [gn36/phpbb-ext-hookup#41]
I received this fatal error everytime I added a group of forum members to a newly created hookup:

Fatal error: Uncaught exception 'Twig_Error_Loader' with message 'Unable to find template "@gn36_hookup/hookup_added.txt" (looked into: ).' in /opt/lampp/htdocs_intern/lanboard_31/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:195 Stack trace: #0 /opt/lampp/htdocs_intern/lanboard_31/phpbb/template/twig/loader.php(107): Twig_Loader_Filesystem->findTemplate('@gn36_hookup/ho...') #1 /opt/lampp/htdocs_intern/lanboard_31/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(138): phpbb\template\twig\loader->findTemplate('@gn36_hookup/ho...') #2 /opt/lampp/htdocs_intern/lanboard_31/vendor/twig/twig/lib/Twig/Environment.php(266): Twig_Loader_Filesystem->getCacheKey('@gn36_hookup/ho...') #3 /opt/lampp/htdocs_intern/lanboard_31/vendor/twig/twig/lib/Twig/Environment.php(324): Twig_Environment->getTemplateClass('@gn36_hookup/ho...', NULL) #4 /opt/lampp/htdocs_intern/lanboard_31/phpbb/template/twig/environment.php(166): Twig_Environment->loadTemplate('@gn36_hookup/ho...', NULL) #5 /opt/lampp/htdocs_intern/lanboard_31/vendor/twig/twig/lib/ in /opt/lampp/htdocs_intern/lanboard_31/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 195

on first place, I thought, that it might be related to the 'add group' feature, since tests with adding single people succeeded always (with my random picked users).
But after some more structured tests, I found out, that the fail is caused by one user, who has set his User language to 'de_x_sie' (Formal german), wheras all other users have 'de' set as their language.
To verify this as the root cause, I cloned the hookup/language/de/ subfolder to hookup/language/de_x_sie/. 
After doing so, the problem with the Fatal Error is gone.

It seems, that the language fallback for the notifications does not work...
Perhaps this is even a phpBB bug and not a problem of the hookup extension?!?

**Comment by gn36** [comment]
I guess you are correct: the problem here would then be that there is no de_x_sie version of the language files so far. Every user will receive the E-Mail in their own language, so you would run into the same problem if you used any other non-existent language such as swedish or russian.

Judging by the error message, this is a problem caused by the missing e-mail templates only, perhaps the language fallback to english does not work for e-mail templates. So in that sense, it is a phpBB problem, but the main problem to be solved remains the missing language, really. It is never nice to have a mixture of multiple languages in your board, and the e-mails are no exception. So you might not even have noticed the problem if the fallback had worked on e-mails as well.

If you wish to have both language versions, please adjust the de version to form the correct de_x_sie version yourself and send me a pull request (or file archive or whatever if you like that better), I'll be happy to include it and make changes to it if needed myself afterwards, but I don't really need it myself so I don't really want to spare the time creating it, at least not right now.

**Comment by BenniGotchi** [comment]
So, I did the 'translation' today and I would be happy to add it...
I'm a little bit new to this git stuff. How do I create such a pull request?
Do I need fork the repository and commit/push the changes to my fork?
Or is it also possible / OK, to directly commit/push the changes to this repos?

**Comment by gn36** [comment]
You will not be able to push to this repository, no. You will have to fork it and then push your changes to that fork. After that, when you go back to the github page of your fork, you will be offered to create a pull request. Then, your pull request will be automatically checked by travis and if it is ok, I will merge it.
