### ISSUE TITLE
Can't see hookup options

### ISSUE THREAD

**Issue by Valiantiam** [gn36/phpbb-ext-hookup#55]
After enabling and confirming that I do have permissions to a specific forum to add hookup events, I do not see any buttons or options to actually add or create the event. Am I missing something else?

**Comment by gn36** [comment]
Yes, probably.
It should look like this: https://www.phpbb.com/customise/db/download/128966 (I hope you can access that since the extension is not yet validated).

Basically, there should be another tab "meeting planner" just below the posting window whenever you create a new topic. In that tab, you can enable the hookup and set a few settings for that particular hookup (automatic reset, self-invite mainly). Then, invitiation of users, setting of text entries or dates is performed after the topic has been created, corresponding interfaces will pop up above the first post on each page of the topic.

A few things to note:
- You have to create a new topic, not just a new post, or you can edit the first post of a topic
- You need to have the corresponding hookup permissions
- You have to use prosilver as your template, others may work if they inherit from prosilver, otherwise you will need to create template files
- Your forum needs to be at least phpBB version 3.1.2, but less than 3.2.0-dev. I have last tested with 3.1.9, so it might be best to update to that.

**Comment by Valiantiam** [comment]
My template inherits from prosilver but it does appear that the extra tab is what I'm missing.

My forums are at version 3.1.9

How could I manually create the template files if I needed to?

**Comment by gn36** [comment]
If it inherits it should usually work, but maybe your template is outdated and misses a template event. Please check if there is an update for your template and for what version of phpBB it actually is. 

Besides that, please check for 
<code></code> 
inside the posting_editor.html of your style.

If it does not exist, that is the error. Fix your style. If your style does not have posting_editor.html, that could mean it is inherited and then it should work the way it is, probably something else is going on then. 

If your style only copied from prosilver, not really inherited, then you can probably fix the issue by simply copying the style/prosilver/ folder inside this extension to style/<yourstylefoldername>/ inside this extension. That is a solution you can always try, I have seen some style inheritance bugs on that stuff in the past and I am not sure whether they were all fixed. If there is any issue with inheritance, this should work.

**Comment by Valiantiam** [comment]
Perfect. I will check to see if I can resolve by doing that and close this with my solution if I find it.

**Comment by Valiantiam** [comment]
![image](https://cloud.githubusercontent.com/assets/5394853/19362949/26aaf9ea-914e-11e6-93fb-7b2e760d062d.png)

Indeed my template in my style did NOT have that event defined. Following how prosilver has it laid out, I was able to determine where it belonged in my style (A style I've purchased a long time ago).

Note to anyone that has this same issue, you must clear your boards cache here:
![image](https://cloud.githubusercontent.com/assets/5394853/19363011/68c334d2-914e-11e6-8656-8cc300009713.png) 
...on your ACP dashboard.

Thanks for the help @gn36 I would not have figured it out without ya.

**Comment by Valiantiam** [comment]
Only have one remaining issue which is that my tab is empty. I think it might still be on my end with my template.

**Comment by gn36** [comment]
Try

> If your style only copied from prosilver, not really inherited, then you can probably fix the issue by simply copying the styles/prosilver/ folder inside this extension to styles/yourstylefoldername/ inside this extension. That is a solution you can always try, I have seen some style inheritance bugs on that stuff in the past and I am not sure whether they were all fixed. If there is any issue with inheritance, this should work.

If your style is different this may cause issues, though. In that case you will have to adjust the file     posting_editor_add_panel_tab.html in styles/yourstylefoldername/template/event/

**Comment by Valiantiam** [comment]
Found it. Was missing 
`<!-- EVENT posting_layout_include_panel_body -->`

in posting_layout.html

Thanks again.... :)
