### ISSUE TITLE
After clicking submit for yes/no/maybe dates, white screen with "ACT"

### ISSUE THREAD

**Issue by Valiantiam** [gn36/phpbb-ext-hookup#56]
![image](https://cloud.githubusercontent.com/assets/5394853/19407250/bbe41122-9261-11e6-9f63-d0a93988203e.png)

![image](https://cloud.githubusercontent.com/assets/5394853/19407253/df97fff2-9261-11e6-969c-7965bde7edda.png)

**Comment by gn36** [comment]
A few questions/remarks to help solve this issue:
1. Is your data stored when you return to the topic later? If so, are notifications sent?
2. What version of this extension are you using? I don't see any reason why "ACT" would be printed on the screen, even if this extension would cause an error and stop the execution. There is no echo command in the extension.
3. What version of phpBB are you using?
4. Are you using other extensions? If so, please disable (no need to delete data!) all other extensions and see if the problem persists.
5. Check if you have access  to the error log of your server and see what error message is logged there that might be causing this white screen.

**Comment by Valiantiam** [comment]
It appears to be the Calendar/Hookup bridge plugin that is causing the issue.

Hookup - 1.0.0-b2-dev
Calendar/Hookup bridge - 1.0.0-dev
phpBB - 3.1.9

**Comment by gn36** [comment]
Ok, then disable that for now or check if you have the current version of it. I am not maintaining development versions that are before an alpha release (which is the case for the bridge), so the version number stays the same even if there are changes.
Also, I didn't keep track of the changes on calendar side since I am not using that myself so maybe there has been an incompatible change.

EDIT: This will happen even if you have the current version. It will only not happen if an active date is set. This is a debug output - the bridge is not finished and might do wonky things. If you wish to experiment, you can go to hjw-bridge/event/listener.php and comment out the lines

> die('ACT');

and 

> die('missing');

This should solve the issue, but I don't know if it has unwanted side effects. **Be careful with the bridge.** It is not finished and I didn't continue development because there are some incompatibilities in the data format of hookup and calendar that can cause inconsistencies in the data (for example, you can have a calendar for each post, but only one hookup per topic, the hookup can have multiple dates per topic, the calendar can have only one date per post).

**Comment by Valiantiam** [comment]
No worries. I've gone ahead and done that.
