### ISSUE TITLE
Random order in case of 'text' choices

### ISSUE THREAD

**Issue by BenniGotchi** [gn36/phpbb-ext-hookup#68]
In case a hookup is created with 'text' choices instead of 'time', the order in which the choices are shown is quite random.

https://github.com/gn36/phpbb-ext-hookup/blob/329a7a8fc354003d1c7e7c09ea3bc4cb1f72bb18/functions/hookup.php#L93-L96

The SQL query grabbing the available choices only gives a meamingful order for the 'time' case, but for the 'text' case the `ORDER BY date_time ASC` has no effect, since date_time is '0' for all entries.

I modified the code on our installation the following way:
`ORDER BY date_time ASC, date_id ASC`

This leads to the behavior, that 'text' type hookups show the options in the order of creation.
For me that sounds like the most reasonable order for this case...

Other opinions?

**Comment by BenniGotchi** [comment]
Sorry, I just noticed, that the topic was already handled/discussed in #61, after I created this issue here  :-( ...

But in regard to @gn36 s question, if sorting for the 'text' in alphabetical order would be the better choice - I think there are many situations, where this is not the best strategy.

In our case we had a bunch of time ranges to choose from:

25.-27.05.2018
01.-03.06.2018
08.-10.06.2018
15.-17.06.2018
...
25.-27.01.2019 
15.-17.02.2019

here a alphabetical / numerical sorting would crash the logical order I guess...

Same if you have options like

minimum, medium, maximum
english, medium rare, medium, medium well, well done

**Comment by gn36** [comment]
Thank you for your argument.

I guess there is always good and bad things about a sorting. I guess ideally, one could pick the sorting for each list or even manually order the items.

I guess we will go for the sorting by ID then, it is for sure better than the current state.

I mainly did not merge the PR from @kilianr because I didn't like the way the sorting was done, functionality wise I think it is for sure better than the current state.
